layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects: personal-website, assignments, bazaar, ael-ohm, Saber-Website, Synth-Trainer-2, Dsackler.github.io
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: GitHub
    web_url: https://github.com/Dsackler
    image_url: https://image.flaticon.com/icons/png/512/25/25231.png

  #- name: Web design

  - name: LinkedIn
    web_url: https://www.linkedin.com/in/david-sackler-80b780194/
    image_url: https://techcrunch.com/wp-content/uploads/2014/02/linkedin_logo.png?w=730&crop=1
